server:
  port: 8083
  servlet:
    session:
      timeout: 72000s

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB 
      max-request-size: 1024MB 
  application:
    name: Parts-Procurement-System
  resources:
    static-locations: classpath:/,file:D:\imgs\
  datasource:
    url: jdbc:mysql://localhost:3308/parts_procurement_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: vnv0123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  http:
    encoding:
      charset: utf-8
      enabled: true

